### ISSUE TITLE
Composer compatibility

### ISSUE THREAD

**Issue by girvo** [Enhance-PHP/Enhance-PHP#14]
Hey all.

I was wondering if [Composer](http://getcomposer.org/) compatibility is on the road-map?

If not, would you accept a PR that created it? I love the test framework, but I'd love to be able to take advantage of Composer's excellent dependency management and Packagist's lovely deployment.

Cheers

**Comment by feamsr00** [comment]
:+1:  for composer support!
I like the intent of this project and I, for one, would like to see EnhancePHP rise from its deep sleep!

**Comment by tbreuss** [comment]
Is this issue still open? I could help here if required.

**Comment by tbreuss** [comment]
I have a first draft for Composer support, see #23.

**Comment by tbreuss** [comment]
Enhance PHP is now available on Packagist: - https://packagist.org/packages/enhance-php/enhance-php

Since we don't have any tags at the moment, you can request the package as follows:

```
composer require enhance-php/enhance-php:dev-main
```

I'll be back in the next few days with specific suggestions for improvement.

**Comment by tbreuss** [comment]
I'm closing this since we have Composer support, a released version, a changelog and a plan.
