### ISSUE TITLE
Running tests in GH pipeline

### ISSUE THREAD

**Issue by tbreuss** [Enhance-PHP/Enhance-PHP#24]
In my fork I've added GitHub pipelines for running Self-Tests of Enhance-PHP with several PHP versions and operating systems.

https://github.com/tbreuss/Enhance-PHP/actions/runs/9157847486

Operating systems:

- ubuntu-latest
- windows-latest
- macos-latest

PHP-Versions:

- 5.6 (last of 5.x)
- 7.4 (last of 7.x)
- 8.0
- 8.1
- 8.2
- 8.3

If you are interested, I can file a pull request, but my other PRs should be merged before.

**Comment by Steve-Fenton** [comment]
Absolutely - I saw you working on updates and loved to see someone getting involved.

**Comment by Steve-Fenton** [comment]
I've done some org set up, so you should be a contributor. I've set up branch protections to run `Self-Tests` on branches prior to a merge. Let me know if anything isn't working as it should.

**Comment by tbreuss** [comment]
I have added matrix tests on Ubuntu, Windows and macOS with several PHP versions from 5.6 to 8.3. In addition, I have also included the examples in the tests. See my comment in pull request #27.

**Comment by Steve-Fenton** [comment]
This is excellent... thank you. 

![Matrix tests in progress](https://github.com/Enhance-PHP/Enhance-PHP/assets/1036595/f3620abf-2fb2-41eb-af85-a51017da8df6)
