### ISSUE TITLE
LF normalization issues with .gitattributes

### ISSUE THREAD

**Issue by tbreuss** [Enhance-PHP/Enhance-PHP#30]
The setup with LF normalization leads to unexpected/strange behavior when checking out from repo or comitting a small edit, at least on macOS.

For example, with this pull request I only wanted to replace the existing ZIP and deleting another one, but had changes for a few PHP files, that I didn't touch at all:

- https://github.com/tbreuss/Enhance-PHP/pull/7/files

I was also struggling with strange issues because you can't see LF changes in some editors (like VSC with my setup).

I for myself would do the following:
- revert the last git commits: 64e59ca9a5fa8a8776228615f42afeb4afbedc14 and 8ca8e2bc5c66565129cb1777fbb3cc0dc14d4ec7
- add an `.editorconfig` like https://github.com/symfony/symfony/blob/7.2/.editorconfig

I think that `.editorconfig` is more common and PHP devs are more comfortable with.

**Comment by Steve-Fenton** [comment]
If we were to add the editor config, would that solve your local problem?

The reason I'm keen on the Git attributes file is that it works even for folks using tools that don't recognize an editor config.

**Comment by tbreuss** [comment]
The editor configuration would not solve the problem, as .editorconfig is basically just a recommendation. But I understand your idea of using .gitattributes as a constraint.

The problem is this: https://github.com/Enhance-PHP/Enhance-PHP/pull/34/files

Although I haven't made any explicit changes, each file has a code change on each line, where the code change contains really just the line feed normalization. 

The bad thing is that Visual Studio Code (or better: Git) forced me to edit and handle these files, and I've tried both versions of VSC on my machine and in codespaces. For the average Git user, it's even more difficult because they can't see obvious code changes.

So, I think the LF thing with .gitattributes is not very helpful.

**Comment by tbreuss** [comment]
Fixed (and normalized) with #34
