### ISSUE TITLE
Website enhance-php.com

### ISSUE THREAD

**Issue by tbreuss** [Enhance-PHP/Enhance-PHP#37]
@Steve-Fenton I was wondering what the status of the https://www.enhance-php.com site is.

I mean, the site looks good, but it's not promoted via the GitHub repository. And we also have https://github.com/Enhance-PHP/Enhance-PHP/wiki. The problem is that you don't know which source is more up-to-date.

Is there a plan regarding the website and documentation?

**Comment by Steve-Fenton** [comment]
The website is a ghost - we gave up the domain in favour of the GitHub wiki, but someone seems to have registered the expired domain and put the site back up. 

My preference would be to move the wiki into a format we can publish on GitHub pages, so it's in the repo along with the code.

**Comment by tbreuss** [comment]
Strange that someone put the site back. For what?

So let's keep the Wiki for the moment and see, how things evolve.
